version: '3.9'

services:
  heartbeat:
    image: beats/heartbeat:${VERSION}
    container_name: heartbeat
    network_mode: host
    env_file: .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - certs:$CERTS_DIR
      - ./configs/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - ./configs/monitors.d:/usr/share/heartbeat/monitors.d:ro

volumes:
  certs:
    external: true
    name: elastic-certs
