# heartbeat.yml
heartbeat.config.monitors:
  path: /usr/share/heartbeat/monitors.d/*.yml
  reload.enabled: true
  reload.period: 10s

heartbeat.scheduler:
  limit: 10

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:localhost:9200}']
  protocol: 'https'
  username: 'heartbeat_writer'
  password: '${HEARTBEAT_WRITER_PASSWORD}'
  ssl:
    certificate_authorities: ["${CERTS_DIR}/kibana/elasticsearch-ca.pem"]
    verification_mode: "certificate"

setup.kibana:
  host: "${KIBANA_HOST:10.1.19.1:9201}"
  protocol: "https"
  username: "heartbeat_setup"
  password: "${HEARTBEAT_SETUP_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CERTS_DIR}/kibana/elasticsearch-ca.pem"]
    verification_mode: "certificate"
